version: '3.7'
services:
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: postgres

  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis:redis:6379
    links:
      - db
      - redis